name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Get Git Commit SHA
      id: git_commit
      run: echo "::set-output name=sha::$(git rev-parse --short HEAD)"

    - name: Build and tag Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/myhello:${{ steps.git_commit.outputs.sha }} .
        docker tag ${{ secrets.DOCKER_USERNAME }}/myhello:${{ steps.git_commit.outputs.sha }} ${{ secrets.DOCKER_USERNAME }}/myhello:latest

    - name: Run Trivy vulnerability scanner on Dockerfile
      uses: aquasecurity/trivy-action@v2
      with:
        image-ref: Dockerfile
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'

    - name: Run Trivy vulnerability scanner on Docker image
      uses: aquasecurity/trivy-action@v2
      with:
        image-ref: ${{ secrets.DOCKER_USERNAME }}/myhello:latest
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'

    - name: Check Trivy results
      run: |
        if [[ ${{ steps.trivy.outputs.exit-code }} -eq 1 ]]; then
          echo "Vulnerabilities found!"
          exit 1
        fi

    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/myhello:${{ steps.git_commit.outputs.sha }}
        docker push ${{ secrets.DOCKER_USERNAME }}/myhello:latest

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
